menu:
  Home: /
  Archives: archives
  page:
    Archives: archives
    Links: links
    About: about

sidePic: https://tva1.sinaimg.cn/large/007S8ZIlgy1ggdmi6yapmj30dw0zk0wm.jpg
avatar: https://tva1.sinaimg.cn/large/007S8ZIlgy1ggdmr1k3k0j305k05k74j.jpg

excerpt_link: 继续阅读
excerpt: 200

social:
  twitter: false
  github: true
  rss: true
  weibo: true

twitter:
  username:

github:
  username:

valine:
  appId: 
  appKey: 